# Usamos la imagen local cp4 como base
FROM cp4

# Establecemos el directorio de trabajo dentro del contenedor
WORKDIR /

# Copiamos el archivo requirements.txt (si lo tienes) al contenedor
COPY requirements.txt requirements.txt

# Instalamos las dependencias listadas en requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# En caso de no tener un requirements.txt, puedes instalar Flask y SQLAlchemy directamente:
# RUN pip install --no-cache-dir Flask SQLAlchemy

# Copiamos el resto de la aplicación al contenedor
#COPY . .

# Exponemos el puerto en el que correrá la aplicación Flask
EXPOSE 8001

# Comando para ejecutar la aplicación
CMD ["python", "app.py"]
